algo:
  name: "QMIX"

env:
  env_id: "mpe.simple_spread_v3"
  is_marl: true
  is_continuous: false
  num_agents: 3
  log_dir: "logs/qmix_simple_spread"
  save_dir: "models/qmix_simple_spread"
  seed: 42

network:
  hidden_dims: [64, 64]
  mixing_embed_dim: 32

buffer:
  capacity: 10000

exploration:
  epsilon_start: 1.0
  epsilon_min: 0.05
  epsilon_decay: 0.99995

target:
  gamma: 0.99
  tau: 1.0 # QMIX traditionally uses hard updates
  update_freq: 200

optim:
  lr: 0.0005
  max_grad_norm: 10.0

training:
  max_steps: 100000
  learning_starts: 1000
  batch_size: 128
  train_freq: 1
  save_freq: 50000
  eval_episodes: 5
