algo:
  name: "DDPG"

env:
  env_id: "Pendulum-v1"
  log_dir: "logs/ddpg_pendulum"
  save_dir: "models/ddpg_pendulum"
  seed: 42
  num_actions: 1
  max_action: 2.0

network:
  hidden_dims: [256, 256]

buffer:
  capacity: 100000 # Off-policy ReplayBuffer

exploration:
  noise_type: "gaussian"
  noise_std: 0.1

target:
  gamma: 0.99
  tau: 0.005 # soft update

optim:
  lr_actor: 0.001
  lr_critic: 0.001
  max_grad_norm: 0.5

training:
  max_steps: 100000
  learning_starts: 2000
  batch_size: 100
  train_freq: 1
  save_freq: 50000
